# Generated by Django 5.0.6 on 2024-08-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('endpoint', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EndpointOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SENDING', 'Sending'), ('QUEUED', 'Queued'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='QUEUED', max_length=100)),
                ('transmit_counter', models.IntegerField(default=0)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('last_attempt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binary', models.FileField(upload_to='firmware')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensordata.endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='FirmwareUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'IDLE'), (1, 'DOWNLOADING'), (2, 'DOWNLOADED'), (3, 'UPDATING')], default=0)),
                ('result', models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'SUCCESS'), (2, 'NO STORAGE'), (3, 'OUT OF MEMORY'), (4, 'CONNECTION LOST'), (5, 'INTEGRITY FAILED'), (6, 'UNSUPPORTED FIRMWARE'), (7, 'INVALID URI'), (8, 'UPDATE FAILED'), (9, 'UNSUPPORTED PROTOCOL')], default=0)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensordata.endpoint')),
                ('execute_operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execute_operation', to='sensordata.endpointoperation')),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensordata.firmware')),
                ('send_uri_operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='send_uri_operation', to='sensordata.endpointoperation')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('str_value', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensordata.endpoint')),
            ],
        ),
        migrations.AddField(
            model_name='endpointoperation',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensordata.resource'),
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('resource_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('TIME', 'int_value'), ('STRING', 'str_value'), ('INTEGER', 'int_value'), ('FLOAT', 'float_value'), ('BOOLEAN', 'int_value')], max_length=50)),
            ],
            options={
                'unique_together': {('object_id', 'resource_id')},
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensordata.resourcetype'),
        ),
        migrations.CreateModel(
            name='EventResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='sensordata.event')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensordata.resource')),
            ],
            options={
                'unique_together': {('event', 'resource')},
            },
        ),
    ]
