# Generated by Django 5.0.6 on 2024-05-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensordata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcetype",
            name="data_type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
