# Generated by Django 5.0.6 on 2024-05-27 22:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sensordata", "0002_alter_resourcetype_data_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="device_id",
            new_name="endpoint",
        ),
        migrations.RemoveField(
            model_name="device",
            name="name",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="bool_value",
        ),
    ]
