# Generated by Django 5.0.1 on 2024-01-28 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sensordata", "0002_sensordata_delete_timetemperature"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensordata",
            old_name="endpoint",
            new_name="ep",
        ),
    ]
