# Generated by Django 5.1 on 2024-09-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0002_alter_firmware_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='timestamp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
