# Generated by Django 5.1 on 2025-07-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0003_alter_resource_timestamp_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='binary_value',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='data_type',
            field=models.CharField(choices=[('TIME', 'int_value'), ('STRING', 'str_value'), ('INTEGER', 'int_value'), ('FLOAT', 'float_value'), ('BOOLEAN', 'int_value'), ('OPAQUE', 'binary_value')], max_length=50),
        ),
    ]
