# Generated by Django 6.0.1 on 2026-01-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0003_alter_resource_timestamp_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='timestamp_created',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
