# Generated by Django 5.0.6 on 2024-06-06 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sensordata",
            "0003_rename_device_id_device_endpoint_remove_device_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "endpoint",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("registered", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name="DeviceOperation",
            new_name="EndpointOperation",
        ),
        migrations.RemoveField(
            model_name="event",
            name="device",
        ),
        migrations.AlterUniqueTogether(
            name="resource",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="event",
            name="endpoint",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="sensordata.endpoint",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resource",
            name="endpoint",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="sensordata.endpoint",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="resource",
            unique_together={("endpoint", "resource_type", "timestamp")},
        ),
        migrations.RemoveField(
            model_name="resource",
            name="device",
        ),
        migrations.DeleteModel(
            name="Device",
        ),
    ]
