# Generated by Django 6.0.1 on 2026-01-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0004_alter_resource_timestamp_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
