# Generated by Django 5.0.1 on 2024-01-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensordata", "0004_rename_ep_sensordata_endpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(default="", max_length=100)),
                ("manufacturer", models.CharField(default="", max_length=100)),
                ("model_number", models.CharField(default="", max_length=100)),
                ("serial_number", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
