# Generated by Django 5.0.6 on 2024-06-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sensordata",
            "0004_endpoint_rename_deviceoperation_endpointoperation_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="endpointoperation",
            old_name="timestamp_sent",
            new_name="timestamp_created",
        ),
        migrations.RenameField(
            model_name="endpointoperation",
            old_name="retransmit_counter",
            new_name="transmit_counter",
        ),
        migrations.AlterField(
            model_name="endpointoperation",
            name="status",
            field=models.CharField(
                choices=[
                    ("SENDING", "Sending"),
                    ("QUEUED", "Queued"),
                    ("CONFIRMED", "Confirmed"),
                    ("FAILED", "Failed"),
                ],
                default="QUEUED",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="resourcetype",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("TIME", "int_value"),
                    ("STRING", "str_value"),
                    ("INTEGER", "int_value"),
                    ("FLOAT", "float_value"),
                    ("BOOLEAN", "int_value"),
                ],
                max_length=50,
            ),
        ),
    ]
