# Generated by Django 5.0.6 on 2024-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0005_rename_timestamp_sent_endpointoperation_timestamp_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointoperation',
            name='last_attempt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='endpointoperation',
            name='timestamp_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
