# Generated by Django 5.0.1 on 2024-01-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensordata", "0005_endpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="factory_reset",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="firmware_version",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="reboot",
            field=models.IntegerField(default=0),
        ),
    ]
