# Generated by Django 5.0.1 on 2024-01-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sensordata",
            "0006_endpoint_factory_reset_endpoint_firmware_version_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="endpoint",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
