# Generated by Django 6.0.1 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensordata", "0006_site_endpoint_site_sitemembership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitemembership",
            name="can_view_firmware",
            field=models.BooleanField(default=False),
        ),
    ]
