# Generated by Django 5.0.6 on 2024-06-14 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sensordata", "0006_alter_endpointoperation_last_attempt_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="end_time",
            new_name="time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_time",
        ),
    ]
