# Generated by Django 5.0.6 on 2024-06-14 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensordata", "0007_rename_end_time_event_time_remove_event_start_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="resource",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="resource",
            name="timestamp_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name="resource",
            name="timestamp",
        ),
    ]
