# Generated by Django 5.0.6 on 2024-07-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0008_alter_resource_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmware',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='firmware',
            name='file_name',
        ),
        migrations.AddField(
            model_name='firmware',
            name='binary',
            field=models.FileField(default='', upload_to='firmware'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firmware',
            name='version',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
