# Generated by Django 5.0.1 on 2024-01-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensordata", "0008_endpoint_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="battery_level",
            field=models.IntegerField(default=0),
        ),
    ]
