# Use the latest stable Redis alpine image
FROM redis:8.4-alpine

# Update and upgrade packages for security patches
RUN apk update && apk upgrade

# Create and set the working directory in the container
WORKDIR /redis

# Copy the configuration and scripts to the container
COPY . /redis/

# Give execution rights on the start-up script
RUN chmod +x /redis/redis_start.sh

# Entry point for the container
ENTRYPOINT ["/redis/redis_start.sh"]
