# Use the official OpenJDK 21 base image
FROM maven:3.9-eclipse-temurin-21

# Set the working directory in the container
WORKDIR /leshan

# Copy the source code, build files, and other necessary files
COPY . /leshan/

# Startup script that handles running Leshan and logging
RUN chmod +x /leshan/leshan_build_run.sh

# Set the entrypoint to your start script
ENTRYPOINT ["/leshan/leshan_build_run.sh"]
