[tox]
envlist = html
skipsdist = true

[testenv]
deps =
    -r requirements.txt
    -r ../server/django/requirements.txt

[testenv:html]
allowlist_externals =
    /bin/sh
commands =
    /bin/sh -c 'rm -rf build/*'
    python ../server/django/manage.py graph_models sensordata -o source/images/erd.svg
    python ../server/django/manage.py generate_openapi -o build/generated/openapi-schema.yaml
    sphinx-build -E -W --keep-going -b html source build/html

[testenv:pdf]
allowlist_externals =
    /bin/sh
commands =
    python ../server/django/manage.py graph_models sensordata -o source/images/erd.svg
    /bin/sh -c 'rm -rf build/pdf/latex/*'
    sphinx-build -M latexpdf source build/pdf
    # Copy the pdf to the static directory so it can be served by the web server
    /bin/sh -c 'mkdir -p build/html/_static/'
    /bin/sh -c 'cp build/pdf/latex/*.pdf build/html/_static/flownexus.pdf'

[testenv:linkcheck]
commands =
    sphinx-build -b linkcheck source build/linkcheck

[testenv:doc]
allowlist_externals =
    /bin/sh
commands =
    /bin/sh -c 'rm -rf build/*'
    python ../server/django/manage.py graph_models sensordata -o source/images/erd.svg
    python ../server/django/manage.py generate_openapi -o build/generated/openapi-schema.yaml
    sphinx-autobuild source build/html --port 8001 --host 0.0.0.0
