services:
  django:
    build:
      context: ./django
      dockerfile: Dockerfile.django
    volumes:
      - ./django:/django
      - ./logs:/django/logs
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      - LESHAN_URI=http://leshan:8080
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:7.2.5
    networks:
      - mynetwork
    ports:
      - "6379:6379"

  leshan:
    build:
      context: ./leshan
      dockerfile: Dockerfile.leshan
    volumes:
      - ./leshan:/leshan
      - ./logs:/leshan/logs
    ports:
      - "5683:5683/udp" # LWM2M default UDP port
      - "5684:5684"     # For LWM2M over DTLS
    networks:
      - mynetwork
    environment:
      - DATA_SENDER_URI=http://django:8000

# Define the custom network
networks:
  mynetwork:
    driver: bridge
