LWM2M_RESOURCE_MAP = {
    (3303, 5700): {"name": "temperature", "data_type": "float"},
    (3303, 5701): {"name": "humidity", "data_type": "float"},
    (3, 0): {"name": "manufacturer", "data_type": "string"},
    (3, 1): {"name": "model_number", "data_type": "string"},
    (3, 2): {"name": "serial_number", "data_type": "string"},
    (3, 3): {"name": "firmware_version", "data_type": "string"},
    (3, 6): {"name": "power_source", "data_type": "int"},
    (3, 7): {"name": "power_source_v", "data_type": "int"},
    (3, 8): {"name": "power_source_i", "data_type": "int"},
    (3, 9): {"name": "battery_level", "data_type": "int"},
    (3, 10): {"name": "memory_free", "data_type": "int"},
    (3, 11): {"name": "error_code", "data_type": "int"},
    (3, 13): {"name": "current_time", "data_type": "time"},
    (3, 14): {"name": "utc_offset", "data_type": "string"},
    (3, 15): {"name": "timezone", "data_type": "string"},
    (3, 16): {"name": "binding_mode", "data_type": "string"},
    (3, 17): {"name": "device_type", "data_type": "string"},
    (3, 18): {"name": "hardware_version", "data_type": "string"},
    (3, 19): {"name": "software_version", "data_type": "string"},
    (3, 20): {"name": "battery_status", "data_type": "int"},
    (3, 21): {"name": "memory_total", "data_type": "int"},
}
