#!/usr/bin/env python3
#
# Copyright (c) 2026 Jonas Remmert
#
# SPDX-License-Identifier: Apache-2.0
#
"""
PurgeCSS wrapper for Tabler CSS optimization.

Downloads the latest Tabler CSS from jsDelivr CDN and removes unused styles
by scanning index.html for class names. Overwrites tabler.min.css with the
purged version.

Usage:
    cd landing && python scripts/purge_css.py

Run this script again after adding new HTML features to regenerate the CSS
with any newly used classes.

Prerequisites:
    npm install -g purgecss
"""

import os
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path
from urllib.request import urlopen

TABLER_VERSION = "1.4.0"
TABLER_CSS_URL = (
    f"https://cdn.jsdelivr.net/npm/@tabler/core@{TABLER_VERSION}/dist/css/tabler.min.css"
)


def check_purgecss():
    """Check if purgecss is installed."""
    try:
        subprocess.run(["purgecss", "--version"], capture_output=True, check=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def download_file(url):
    """Download a file from URL and return content."""
    print(f"Downloading Tabler v{TABLER_VERSION} from jsDelivr...")
    with urlopen(url) as response:
        content = response.read().decode("utf-8")
    print(f"  Downloaded {len(content.encode('utf-8')) / 1024:.1f} KB")
    return content


def get_file_size_kb(path):
    """Get file size in KB."""
    size_bytes = os.path.getsize(path)
    return size_bytes / 1024


def run_purgecss(input_css_path, output_css_path, content_html):
    """Run PurgeCSS to remove unused styles."""
    cmd = [
        "purgecss",
        "--css",
        input_css_path,
        "--content",
        content_html,
        "--output",
        output_css_path,
        "--safelist",
        "html",
        "body",
    ]

    print("Running PurgeCSS...")
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print("Error running PurgeCSS:")
        print(result.stderr)
        sys.exit(1)

    print("  Purge complete")


def add_comment_header(css_path, original_size_kb):
    """Add comment header with version info and stats."""
    purged_size_kb = get_file_size_kb(css_path)
    reduction_pct = ((original_size_kb - purged_size_kb) / original_size_kb) * 100

    header = f"""/*
 * Tabler CSS - Purged for flownexus landing page
 *
 * Original version: @tabler/core@{TABLER_VERSION}
 * Source URL: {TABLER_CSS_URL}
 * Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
 *
 * This file was automatically generated by purge_css.py.
 * To regenerate (e.g., after adding new HTML features):
 *   cd landing && python scripts/purge_css.py
 *
 * Size comparison:
 *   Original:  {original_size_kb:.1f} KB
 *   Purged:    {purged_size_kb:.1f} KB  ({reduction_pct:.1f}% reduction)
 */

"""

    with open(css_path, encoding="utf-8") as f:
        content = f.read()

    with open(css_path, "w", encoding="utf-8") as f:
        f.write(header + content)


def main():
    # Get paths relative to script location
    script_dir = Path(__file__).parent.resolve()
    landing_dir = script_dir.parent.resolve()
    assets_dir = landing_dir / "assets"
    html_path = landing_dir / "index.html"
    css_path = assets_dir / "tabler.min.css"

    # Ensure assets directory exists
    assets_dir.mkdir(exist_ok=True)

    # Check for PurgeCSS
    if not check_purgecss():
        print("Error: PurgeCSS is not installed.")
        print("Please install it with: npm install -g purgecss")
        sys.exit(1)

    # Download Tabler CSS to temp file
    css_content = download_file(TABLER_CSS_URL)
    original_size_kb = len(css_content.encode("utf-8")) / 1024

    with tempfile.NamedTemporaryFile(mode="w", suffix=".css", delete=False) as tmp:
        tmp.write(css_content)
        tmp_path = tmp.name

    purged_tmp_path = None
    try:
        # Run PurgeCSS to temp output
        with tempfile.NamedTemporaryFile(mode="w", suffix=".css", delete=False) as tmp_out:
            purged_tmp_path = tmp_out.name

        run_purgecss(tmp_path, purged_tmp_path, str(html_path))

        # Move purged CSS to final location
        shutil.move(purged_tmp_path, css_path)

        # Add comment header
        add_comment_header(css_path, original_size_kb)

    finally:
        # Cleanup temp files
        os.unlink(tmp_path)
        # Note: purged_tmp_path is moved (not copied), so it no longer exists at source
        # Only cleanup if something went wrong and file still exists
        if purged_tmp_path and os.path.exists(purged_tmp_path):
            os.unlink(purged_tmp_path)

    print(f"\nDone! Purged CSS saved to: {css_path}")
    print("\nRun this script again after adding new HTML features.")


if __name__ == "__main__":
    main()
