# Use the official lightweight Python image.
FROM docker.io/library/python:3.13-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Accept version as a build argument and set it as an environment variable
ARG APP_VERSION=unknown
ENV APP_VERSION=${APP_VERSION}

# Create and set the working directory in the container
WORKDIR /django

# Install dependencies
COPY requirements.txt /django/
RUN pip install --no-cache-dir -r /django/requirements.txt

# Copy the rest of the code
COPY . /django/

# Collect static files
RUN python manage.py collectstatic --noinput

# Give execution rights on the start-up script
RUN chmod +x /django/django_start.sh

# Configure the container to run in an executed manner, replace "myproject" with your Django project name
ENTRYPOINT ["/django/django_start.sh"]
