[tox]
envlist = unit-tests
skipsdist = True

[testenv:unit-tests]
basepython = python3.13
deps =
    -rrequirements.txt
setenv =
    DJANGO_SETTINGS_MODULE = core.settings
commands =
    python -c "import os; os.makedirs('static_collect', exist_ok=True)"
    pytest sensordata/tests/ frontend/tests.py
