name: Build Sphinx Doc

on:
  pull_request:

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install default-jre plantuml graphviz texlive-latex-extra texlive-xetex latexmk imagemagick librsvg2-bin -y

    - name: Build static site
      run: |
        make doc-html
        make doc-pdf
