name: Compliance Checks

on:
  pull_request:

jobs:
  compliance-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run compliance checks
        env:
          BASE_REF: ${{ github.base_ref }}
        run: |
            git fetch origin $BASE_REF
            make compliance
