name: Build and Deploy Sphinx Doc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install default-jre plantuml graphviz jq tox texlive-latex-extra texlive-xetex latexmk python3-pip -y

      - name: Build static site
        run: |
          make doc-html
          make doc-pdf

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html
