name: Build and Deploy Sphinx Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Java
      run: sudo apt-get update && sudo apt-get install -y default-jre

    - name: Install PlantUML
      run: sudo apt-get install -y plantuml

    - name: Install Tox
      run: pip install tox

    - name: Build static site with Tox
      run: |
        cd doc
        tox -e py3-html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/build/html
