name: Build and Deploy Sphinx Doc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y default-jre plantuml tox
      - name: Build static site with Tox
        run: |
          cd doc
          tox -e py3-html
          cd ..
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html
